<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE uczelnia [
	<!ENTITY pri "prof. dr hab. inż.">
	<!ENTITY prnain "dr hab. inż., prof. nadzw.">
	<!ENTITY prna "dr hab., prof. nadzw.">
	<!ENTITY prdr "prof. dr hab.">
	<!ENTITY dri "dr inż.">
	<!ENTITY drhi "dr hab. inż.">
	<!ENTITY w "wyklad">
	<!ENTITY c "ćwiczenia">
	<!ENTITY l "laboratoria">
	<!ENTITY p "projekt">

	<!ELEMENT uczelnia   (nazwa, rektor, prorektor, prorektor, wydzial, wydzial+, katedra*, biblioteka?)>

	<!ELEMENT nazwa      (#PCDATA)>
	<!ELEMENT rektor     (imie, nazwisko, tytul)>
	<!ELEMENT prorektor  (imie, nazwisko, tytul)>
	<!ELEMENT imie       (#PCDATA)>
	<!ELEMENT nazwisko   (#PCDATA)>
	<!ELEMENT tytul      (#PCDATA)>
	<!ELEMENT wydzial    (nazwa, dziekan, prodziekan*, instytut+, kierunek+)>
	<!ELEMENT dziekan    (imie, nazwisko, tytul)>
	<!ELEMENT prodziekan (imie, nazwisko, tytul)>
	<!ELEMENT instytut   (nazwa, szef)>
	<!ELEMENT szef       (imie, nazwisko, tytul)>
	<!ELEMENT kierunek   (nazwa, kurs+)>
	<!ELEMENT kurs       (nazwa, opis, forma+)>
	<!ELEMENT opis       (#PCDATA)>
	<!ELEMENT forma      (#PCDATA)>
	<!ELEMENT katedra    (nazwa, szef)>
	<!ELEMENT biblioteka (#PCDATA)>
]>

<uczelnia>
  <nazwa>Politechnika Wrocławska</nazwa>
  <rektor>
    <imie>Andrzej</imie>
    <nazwisko>Mulak</nazwisko>
    <tytul> &pri; </tytul>
 </rektor>
 <prorektor>
    <imie>Jerzy</imie>
    <nazwisko>Zdanowski</nazwisko>
    <tytul> &pri; </tytul>
 </prorektor>
 <prorektor>
    <imie>Jerzy</imie>
    <nazwisko>Świątek</nazwisko>
    <tytul> &prna; </tytul>
 </prorektor>
 <wydzial>
    <nazwa>Informatyki i Zarządzania</nazwa>
    <dziekan>
      <imie>Tadeusz</imie>
      <nazwisko>Galanc</nazwisko>
      <tytul> &prdr; </tytul>
   </dziekan>
   <prodziekan>
      <imie>Zygmunt</imie>
      <nazwisko>Mazur</nazwisko>
      <tytul> &prna; </tytul>
   </prodziekan>
   <prodziekan>
      <imie>Marian</imie>
      <nazwisko>Molasy</nazwisko>
      <tytul> &dri; </tytul>
   </prodziekan>
   <instytut>
      <nazwa>Instytut Organizacji i Zarządzania</nazwa>
      <szef>
        <imie>Janusz</imie>
        <nazwisko>Kroik</nazwisko>
        <tytul> &dri; </tytul>
     </szef>
   </instytut>
    <instytut>
      <nazwa>Instytut Sterowania i Techniki Systemów</nazwa>
      <szef>
        <imie>Adam</imie>
        <nazwisko>Grzech</nazwisko>
        <tytul> &prnain; </tytul>
     </szef>
   </instytut>

    <kierunek>
      <nazwa>Informatyka</nazwa>
      <kurs>
        <nazwa>Algorytmy i struktury danych</nazwa>
        <opis>Podstawowe algorytmy oraz statyczne i dynamiczne struktury danych wykorzystywanych w informatyce
       </opis>
        <forma> &w; </forma>
        <forma> &c; </forma>
        <forma> &l; </forma>
     </kurs>
      <kurs>
        <nazwa>Wstęp do programowania</nazwa>
        <opis>Podstawy programowania na przykładzie języka pascal</opis>
        <forma> &w;</forma>
        <forma> &c; </forma>
        <forma> &l; </forma>
     </kurs>

          <!-- pozostałe kursy -->
   </kierunek>
        <!-- pozostałe kierunki -->
 </wydzial>

  <wydzial>
    <nazwa>Mechaniczny</nazwa>
    <dziekan>
      <imie>Jan</imie>
      <nazwisko>Koch</nazwisko>
      <tytul> &pri; </tytul>
   </dziekan>
    <prodziekan>
      <imie>Jerzy</imie>
      <nazwisko>Bochman</nazwisko>
      <tytul> &dri; </tytul>
   </prodziekan>
    <prodziekan>
      <imie>Jan</imie>
      <nazwisko>Wojciechowski</nazwisko>
      <tytul> &drhi; </tytul>
   </prodziekan>
    <instytut>
      <nazwa>Instytut Konstrukcji i Eksploatacji Maszyn</nazwa>
      <szef>
        <imie>Wacław</imie>
        <nazwisko>Kollek</nazwisko>
        <tytul> &pri; </tytul>
     </szef>
   </instytut>
    <kierunek>
      <nazwa>Automatyka i robotyka</nazwa>
      <kurs><nazwa>Podstawy konstrukcji maszyn </nazwa>
        <opis/>
        <forma> &w; </forma>
        <forma> &p;</forma>
     </kurs>
   </kierunek>
 </wydzial>

  <!-- pozostałe wydziały oraz katedry, jak również biblioteka -->

</uczelnia>
