=== okoniewskid/University_work/Bachelors/Year_2/XML/04.Wiele do jednego, czyli o przestrzeniach nazw i encjach/sklep.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT sklep (dzialy, produkty)>

<!ELEMENT dzialy (dzial+)>

<!ELEMENT produkty (produkt+)>
<!ELEMENT produkt (nazwa, ilosc)>

<!ELEMENT dzial (#PCDATA)>
<!ELEMENT nazwa (#PCDATA)>
<!ELEMENT ilosc (#PCDATA)>

<!ATTLIST dzial 
	skrot ID #REQUIRED>
<!ATTLIST produkt
	kod ID #REQUIRED
	dzial_skrot IDREF #REQUIRED>

=== okoniewskid/University_work/Bachelors/Year_2/XML/04.Wiele do jednego, czyli o przestrzeniach nazw i encjach/lab4dok2A.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE sklep SYSTEM "sklep.dtd">
<sklep>
    <dzialy>
	   	<dzial skrot="ch">chemiczny</dzial>
		<dzial skrot="sp">spożywczy</dzial>
		<dzial skrot="mi">mięsny</dzial>
	</dzialy>
	<produkty>
		<produkt kod="pl1344" dzial_skrot="cghh">
			<nazwa>Płyn Ludwik</nazwa>
			<ilosc>30</ilosc>
		</produkt>
		<produkt kod="bk531" dzial_skrot="sp">
			<nazwa>Bułka Kajzerka</nazwa>
			<ilosc>40</ilosc>
		</produkt>
		<produkt kod="ps232" dzial_skrot="mi">
			<nazwa>Polędwica Sopocka</nazwa>
			<ilosc>4.5</ilosc>
		</produkt>
		<produkt kod="pc898" dzial_skrot="ch">
			<nazwa>Pasta Colgate</nazwa>
			<ilosc>5</ilosc>
		</produkt>
		<produkt kod="sd12343" dzial_skrot="sp">
			<nazwa>Serek Danio</nazwa>
			<ilosc>15</ilosc>
		</produkt>
	</produkty>
</sklep>
