=== okoniewskid/University_work/Bachelors/Year_2/XML/08.XML Schema - odwołania, grupy, wartości niepowtarzalne/hotel.xsd
<?xml version="1.0" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
 
<xsd:element name="hotel">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element ref="pokoje"/>
			<xsd:element ref="rezerwacje"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:unique name="pokoj">
		<xsd:selector xpath="pokoje/pokoj"/>
		<xsd:field xpath="@nr"/>
	</xsd:unique>
	
	<xsd:key name="unikatowynrpokoju">
		<xsd:selector xpath="pokoje/pokoj"/>
		<xsd:field xpath="@nr"/>
	</xsd:key>
	
	 <xsd:keyref name="nrpokoju" refer="unikatowynrpokoju">
		 <xsd:selector xpath="rezerwacje/rezerwacja"/>
		<xsd:field xpath="@id"/>
	 </xsd:keyref>
	
</xsd:element>
			<xsd:element name="pokoje">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="pokoj" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="ilosc_osob" type="xsd:integer"/>
									<xsd:element name="cena" type="xsd:decimal"/>
									<xsd:element name="rodzaj_lozka" type="xsd:string"/>
									<xsd:element name="tv" type="xsd:string"/>
									<xsd:element name="internet" type="xsd:string"/>
								</xsd:sequence>
								<xsd:attribute name="nr" type="xsd:integer"/>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			
			<xsd:element name="rezerwacje">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="rezerwacja" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="data_rezerwacji" type="xsd:date"/>
									<xsd:element name="data_zameldowania" type="xsd:date"/>
									<xsd:element name="data_wymeldowania" type="xsd:date"/>
								</xsd:sequence>
								<xsd:attribute name="id" type="xsd:integer"/>
								<xsd:attribute name="nr_pokoju" type="xsd:integer"/>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>			
</xsd:schema>

=== okoniewskid/University_work/Bachelors/Year_2/XML/08.XML Schema - odwołania, grupy, wartości niepowtarzalne/hotel.xml
<?xml version="1.0"?>

<hotel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="hotel.xsd">

	<pokoje>
		
		<pokoj nr="1">
			<ilosc_osob>3</ilosc_osob>
			<cena>1500</cena>
			<rodzaj_lozka>duze</rodzaj_lozka>
			<tv>tak</tv>
			<internet>wifi</internet>
		</pokoj>
		<pokoj nr="2">
			<ilosc_osob>1</ilosc_osob>
			<cena>500</cena>
			<rodzaj_lozka>male</rodzaj_lozka>
			<tv>tak</tv>
			<internet>kabel</internet>
		</pokoj>
		<pokoj nr="3">
			<ilosc_osob>4</ilosc_osob>
			<cena>2000</cena>
			<rodzaj_lozka>srednie</rodzaj_lozka>
			<tv>tak</tv>
			<internet>brak</internet>
		</pokoj>
	</pokoje>
	
	<rezerwacje>
		
		<rezerwacja id="1">
			<data_rezerwacji>2012-04-20</data_rezerwacji>
			<data_zameldowania>2012-06-12</data_zameldowania>
			<data_wymeldowania>2012-07-20</data_wymeldowania>
		</rezerwacja>
		
		<rezerwacja id="2">
			<data_rezerwacji>2012-04-18</data_rezerwacji>
			<data_zameldowania>2012-06-21</data_zameldowania>
			<data_wymeldowania>2012-07-21</data_wymeldowania>
		</rezerwacja>
		
		<rezerwacja id="2">
			<data_rezerwacji>2012-02-21</data_rezerwacji>
			<data_zameldowania>2012-05-21</data_zameldowania>
			<data_wymeldowania>2012-07-21</data_wymeldowania>
		</rezerwacja>
		
		<rezerwacja id="3">
			<data_rezerwacji>2012-01-21</data_rezerwacji>
			<data_zameldowania>2012-04-21</data_zameldowania>
			<data_wymeldowania>2012-07-21</data_wymeldowania>
		</rezerwacja>
		
		<rezerwacja id="3">
			<data_rezerwacji>2012-01-21</data_rezerwacji>
			<data_zameldowania>2012-03-21</data_zameldowania>
			<data_wymeldowania>2012-07-21</data_wymeldowania>
		</rezerwacja>
		
	</rezerwacje>
	</hotel>
