=== okoniewskid/University_work/Bachelors/Year_2/XML/03.DTD - szablony dla plików XML/pracownik.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT pracownicy (dzial_spozywczy, dzial_chemiczny)>
<!ELEMENT dzial_spozywczy (pracownik*)>
<!ELEMENT dzial_chemiczny (pracownik+)>
<!ELEMENT pracownik (nazwisko, imie, data_zatr)>
<!ATTLIST pracownik
plec (m|k|bd) "bd"
pesel NMTOKEN #REQUIRED
status CDATA #IMPLIED>
<!ELEMENT nazwisko (#PCDATA)>
<!ELEMENT imie (#PCDATA)>
<!ELEMENT data_zatr (#PCDATA)>

=== okoniewskid/University_work/Bachelors/Year_2/XML/03.DTD - szablony dla plików XML/pracownicy.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE pracownicy SYSTEM "pracownik.dtd">
<pracownicy>
	<dzial_spozywczy>
		<pracownik plec="m" pesel='8707140112' status='przydatny'>
			<nazwisko> Nowak </nazwisko>
			<imie> Michał </imie>
			<data_zatr> 10-01-2009 </data_zatr>
		</pracownik>
		<pracownik plec="k"  status='wytrwała'>
			<nazwisko> Lipiec </nazwisko>
			<imie> Anna </imie>
			<data_zatr> 04-12-2007 </data_zatr>
		</pracownik>
	</dzial_spozywczy>
	<dzial_chemiczny>
		<pracownik plec="k" pesel='92041245875' status='obibok'>
			<nazwisko> Malinowska </nazwisko>
			<imie> Marta </imie>
			<data_zatr> 23-06-2005 </data_zatr>
		</pracownik>
		<pracownik plec="m" pesel='91031443825' status='kierownik'>
			<nazwisko> Adrian </nazwisko>
			<imie> Chorzelewski </imie>
			<data_zatr> 23-06-2014 </data_zatr>
		</pracownik>
		<pracownik plec="bd" pesel='91021341472' status='sprzątacz'>
			<nazwisko> Adamczyk </nazwisko>
			<imie> Adam </imie>
			<data_zatr> 12-04-2011 </data_zatr>
		</pracownik>
	</dzial_chemiczny>
</pracownicy>
